# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shoggot test site
email: iopden@gmail.com
description: > This site is for testing new skills in HTML/CSS.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shoggot.pp.ua" # the base hostname & protocol for your site
twitter_username: shoggotden
github_username:  shoggotden

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
